name: microservices-test

services:
  api-gateway:
    container_name: api-gateway
    environment:
      - NODE_ENV=develop
      - PORT=3003
      - CORS=true
      - JWT_SECRET=secret0sUp
      - AMQP_URL=amqp://user:password@rabbitmq
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/test-db
    build:
      context: .
      args:
        - APP=api-gateway
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - 3003:3003

  core:
    container_name: core
    environment:
      - NODE_ENV=develop
      - CORS=true
      - JWT_SECRET=secret0sUp
      - AMQP_URL=amqp://user:password@rabbitmq
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/test-db
    build:
      context: .
      args:
        - APP=core
    restart: always
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    container_name: postgres
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: test-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13.4-management-alpine
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

volumes:
  rabbitmq:
  postgres:

networks:
  default:
    name: test-network
