export enum RabbitMQ {
  APIGateway = 'api-gateway-rmq',
  CoreQueue = 'core-rmq',
}

export enum UserMsg {
  CREATE = 'CREATE_USER',
  FIND_ALL = 'FIND_USERS',
  FIND_ONE = 'FIND_ONE_USER',
  UPDATE = 'UPDATE_USER',
  DELETE = 'DELETE_USER',
  VALID_USER = 'VALID_USER',
  VALID_TOKEN_USER = 'VALID_TOKEN_USER',
  UPDATE_AVATAR = 'UPDATE_AVATAR_USER',
  FIND_POSTS = 'FIND_POSTS_USER',
}

export enum PostMsg {
  CREATE = 'CREATE_POST',
  FIND_ALL = 'FIND_POSTS',
  FIND_ONE = 'FIND_ONE_POST',
  UPDATE = 'UPDATE_POST',
  DELETE = 'DELETE_POST',
  FIND_BY_USER = 'FIND_BY_USER_POSTS',
}
